In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def tinggi(kiri,kanan,x):
    if x<=kiri:
        return 0
    elif x>kanan:
        return 1
    return (x-kiri)/(kanan-kiri)
def rendah(kiri,kanan,x):
    if x<=kiri:
        return 1
    elif x>kanan:
        return 0
    return 1-((x-kiri)/(kanan-kiri))
def sedang(kiri1,kiri2,kanan1,kanan2,x):
    if x<=kiri1 or x>kanan2:
        return 0
    elif x>kiri1 and x<=kiri2:
        return (x-kiri1)/(kiri2-kiri1)
    elif x>kiri2 and x<=kanan1:
        return 1
    elif x>kanan1 and x<=kanan2:
        return (kanan2-x)/(kanan2-kanan1)
    return 0

df=pd.read_csv("DataTugas2.csv")

In [20]:
tpkiri=1.5
tpkanan=1.75
rpkiri=0.5
rpkanan=0.75
spkiri1=0.65
spkiri2=0.8
spkanan1=1.4
spkanan2=1.65
thkiri=70
thkanan=80
rhkiri=20
rhkanan=30
shkiri1=25
shkiri2=35
shkanan1=65
shkanan2=75

df2=df
df2['considered'] = df.apply(lambda row: max(min(tinggi(tpkiri,tpkanan,row[' Pendapatan']),tinggi(thkiri,thkanan,row[' Hutang'])),
    min(sedang(spkiri1,spkiri2,spkanan1,spkanan2,row[' Pendapatan']),sedang(shkiri1,shkiri2,shkanan1,shkanan2,row[' Hutang'])),
    min(rendah(rpkiri,rpkanan,row[' Pendapatan']),rendah(rhkiri,rhkanan,row[' Hutang']))), axis=1)
df2['accepted'] = df.apply(lambda row: max(min(sedang(spkiri1,spkiri2,spkanan1,spkanan2,row[' Pendapatan']),tinggi(thkiri,thkanan,row[' Hutang'])),
    min(rendah(rpkiri,rpkanan,row[' Pendapatan']),tinggi(thkiri,thkanan,row[' Hutang'])),
    min(rendah(rpkiri,rpkanan,row[' Pendapatan']),sedang(shkiri1,shkiri2,shkanan1,shkanan2,row[' Hutang']))), axis=1)
df2['rejected'] = df.apply(lambda row: max(min(tinggi(tpkiri,tpkanan,row[' Pendapatan']),sedang(shkiri1,shkiri2,shkanan1,shkanan2,row[' Hutang'])),
    min(tinggi(tpkiri,tpkanan,row[' Pendapatan']),rendah(rhkiri,rhkanan,row[' Hutang'])),
    min(sedang(spkiri1,spkiri2,spkanan1,spkanan2,row[' Pendapatan']),rendah(rhkiri,rhkanan,row[' Hutang']))), axis=1)

In [41]:
def deffuzy(r, c, a):
    return ((r * 40) + (c * 60) + (a * 90))/(r+c+a)
df2['score'] = df.apply(lambda row: deffuzy(row['rejected'],row['considered'],row['accepted']), axis=1)

In [50]:
df2=df2.sort_values(by=['score'], ascending=False)
# print(df2)
i=0
has=[]
for index, row in df2.iterrows():
    if i<20:
        has.append(index+1)
    i+=1
# print(has)
expor = pd.DataFrame({'No':has})

# print(expor)
expor.to_csv("hasil.csv", encoding='utf-8', index=False)
#     print(row['No'], row['score'])

    No   Pendapatan   Hutang  considered  accepted  rejected      score
61  62        1.159   87.871    0.000000    1.0000  0.000000  90.000000
48  49        0.516   43.660    0.000000    0.9360  0.000000  90.000000
2    3        1.273   80.701    0.000000    1.0000  0.000000  90.000000
60  61        0.880   79.878    0.000000    0.9878  0.000000  90.000000
63  64        0.588   35.480    0.000000    0.6480  0.000000  90.000000
17  18        1.345   76.343    0.000000    0.6343  0.000000  90.000000
18  19        0.599   45.566    0.000000    0.6040  0.000000  90.000000
46  47        0.780   78.054    0.000000    0.8054  0.000000  90.000000
73  74        0.600   80.864    0.000000    0.6000  0.000000  90.000000
47  48        1.433   78.028    0.000000    0.8028  0.000000  90.000000
14  15        0.428   38.739    0.000000    1.0000  0.000000  90.000000
76  77        1.217   82.991    0.000000    1.0000  0.000000  90.000000
33  34        0.515   41.771    0.000000    0.9400  0.000000  90.000000
35  36        0.946   98.000    0.000000    1.0000  0.000000  90.000000
92  93        0.557   29.517    0.048300    0.4517  0.000000  87.102000
20  21        0.155   29.496    0.050400    0.4496  0.000000  86.976000
5    6        0.664   63.226    0.093333    0.3440  0.000000  83.597561
79  80        0.664   39.692    0.093333    0.3440  0.000000  83.597561
65  66        0.666   60.245    0.106667    0.3360  0.000000  82.771084
52  53        0.473   28.740    0.126000    0.3740  0.000000  82.440000
58  59        0.493   27.813    0.218700    0.2813  0.000000  76.878000
3    4        1.534   73.641    0.136000    0.3641  0.135900  72.900943
94  95        1.329   71.308    0.369200    0.1308  0.000000  67.848000
22  23        0.112   26.202    0.379800    0.1202  0.000000  67.212000
34  35        1.325   70.009    0.499100    0.0009  0.000000  60.054000
30  31        0.632   20.042    0.472000    0.0000  0.000000  60.000000
40  41        1.159   68.120    0.688000    0.0000  0.000000  60.000000
97  98        1.406   46.838    0.976000    0.0000  0.000000  60.000000
8    9        0.806   69.192    0.580800    0.0000  0.000000  60.000000
59  60        0.765   36.031    0.766667    0.0000  0.000000  60.000000
..  ..          ...      ...         ...       ...       ...        ...
54  55        1.623   41.850    0.108000    0.0000  0.492000  43.600000
37  38        0.747   25.471    0.047100    0.0120  0.452900  43.011719
0    1        1.632   39.375    0.072000    0.0000  0.528000  42.400000
71  72        1.641   46.775    0.036000    0.0000  0.564000  41.200000
84  85        1.030   25.246    0.024600    0.0000  0.475400  40.984000
83  84        1.643   57.308    0.028000    0.0000  0.572000  40.933333
25  26        1.410   25.133    0.013300    0.0000  0.486700  40.532000
57  58        0.748   23.649    0.008000    0.0000  0.635100  40.248795
96  97        0.950   23.790    0.000000    0.0000  0.621000  40.000000
6    7        1.680   37.761    0.000000    0.0000  0.720000  40.000000
7    8        0.925    0.000    0.000000    0.0000  1.000000  40.000000
70  71        1.046   13.541    0.000000    0.0000  1.000000  40.000000
74  75        0.894   22.836    0.000000    0.0000  0.716400  40.000000
24  25        1.723   33.533    0.000000    0.0000  0.853300  40.000000
36  37        1.755   42.045    0.000000    0.0000  1.000000  40.000000
44  45        1.736   27.340    0.000000    0.0000  0.266000  40.000000
28  29        1.684   45.068    0.000000    0.0000  0.736000  40.000000
80  81        1.164   18.112    0.000000    0.0000  1.000000  40.000000
19  20        1.763   55.289    0.000000    0.0000  1.000000  40.000000
29  30        1.794   24.110    0.000000    0.0000  0.589000  40.000000
49  50        1.818   49.628    0.000000    0.0000  1.000000  40.000000
98  99        0.816   18.123    0.000000    0.0000  1.000000  40.000000
78  79        1.227   20.851    0.000000    0.0000  0.914900  40.000000
45  46        1.714   36.429    0.000000    0.0000  0.856000  40.000000
53  54        0.756   11.764    0.000000    0.0000  0.706667  40.000000
90  91        0.793   11.302    0.000000    0.0000  0.953333  40.000000
81  82        1.804   27.693    0.000000    0.0000  0.269300  40.000000
77  78        1.900   32.769    0.000000    0.0000  0.776900  40.000000
68  69        1.218   17.396    0.000000    0.0000  1.000000  40.000000
85  86        1.531   21.480    0.000000    0.0000  0.476000  40.000000

[100 rows x 7 columns]
[62, 49, 3, 61, 64, 18, 19, 47, 74, 48, 15, 77, 34, 36, 93, 21, 6, 80, 66, 53]
    No
0   62
1   49
2    3
3   61
4   64
5   18
6   19
7   47
8   74
9   48
10  15
11  77
12  34
13  36
14  93
15  21
16   6
17  80
18  66
19  53